version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 10
    target-branch: "develop"

  - package-ecosystem: "cargo"
    directory: "/internal"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 10
    target-branch: "develop"

  - package-ecosystem: "bun"
    directory: "/internal/dashboard/ui"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "dashboard"
    open-pull-requests-limit: 10
    target-branch: "develop"
    groups:
      types:
        patterns: ["@types/*"]
      tailwind:
        patterns: ["tailwindcss", "@tailwindcss/*"]
