pub mod client;
pub mod handlers;
pub mod heartbeat;
pub mod router;
pub mod wg;
pub mod ws_hub;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct Agent {
    pub id: Uuid,
    pub name: String,
    pub wg_pubkey: String,
    pub wg_ip: String,
    pub wg_endpoint: Option<String>,
    pub api_port: i32,
    pub status: String,
    pub version: Option<String>,
    pub last_heartbeat: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
pub struct RegisterAgentRequest {
    /// UUID v7 generated by the agent install script
    pub agent_id: Uuid,
    pub name: String,
    /// Agent's WireGuard public key (base64)
    pub wg_pubkey: String,
    /// Agent VPS public IP (for WG endpoint display)
    pub wg_endpoint: Option<String>,
    pub api_port: Option<i32>,
    /// Set to true when registering the agent running on the same VPS as the dashboard.
    pub is_local_agent: Option<bool>,
}

#[derive(Debug, Serialize)]
pub struct AgentSummary {
    pub id: Uuid,
    pub name: String,
    pub status: String,
    pub wg_ip: String,
    pub version: Option<String>,
    pub last_heartbeat: Option<DateTime<Utc>>,
}

/// Returned after successful agent registration.
/// `sync_token`, `cert`, and X.509 material are shown once.
#[derive(Debug, Serialize)]
pub struct RegisterAgentResponse {
    #[serde(flatten)]
    pub agent: Agent,
    pub sync_token: String,
    /// JSON-signed certificate for this agent — agent uses to verify command authority
    pub cert: crate::crypto::pki::SignedCert,
    /// CA Ed25519 public key (base64url) — for JSON cert verification
    pub ca_public_key: String,
    /// X.509 agent server certificate DER (base64) — for mTLS listener
    pub tls_cert_der: String,
    /// X.509 agent private key DER PKCS#8 (base64) — for mTLS listener
    pub tls_key_der: String,
    /// X.509 CA certificate DER (base64) — agent verifies dashboard client certs against this
    pub tls_ca_cert_der: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AuditSyncEntry {
    pub id: Uuid,
    pub agent_id: Uuid,
    pub organization_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub command_type: String,
    pub result: String,
    pub error: Option<String>,
    pub previous_hash: String,
    pub entry_hash: String,
    pub created_at: DateTime<Utc>,
}
